Make the scheduler aware of KEVs
cisagov/cyhy-core pull request #64
Opened 2022-04-04 19:13 UTC by felddy

#  #

## 🗣 Description ##

This PR makes the scheduler aware of the KEV field in tickets.
As per the requirements, when a host has a ticket with `details.kev` set to `true` the scheduler will schedule this with the same priority as a critical vulnerability.

## 💭 Motivation and context ##

These changes makes no sense.  I have no idea why we are doing it.
All vulnerabilities that end up in the "Known Exploited" catalog will already have high priorities from their CVSS scores.

Closing language:
- Closes cisagov/cyhy-system#44
- Closes cisagov/cyhy-system#45 

## 🧪 Testing ##

- [ ] Tested by scanning a host with a vulnerability that is listed in the KEV but no other concurrent criticals on the same host.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] All new and existing tests pass.

2022-04-04 21:20 UTC, dav3r approved these changes
Excellent 👍

2022-04-05 05:32 UTC, mcdonnnj requested changes
Straightforward 👍 I had some housekeeping suggestions for your consideration.

2022-04-05 05:32 UTC, mcdonnnj commented on cyhy/db/scheduler.py
> +from cyhy.db.queries import max_severity_for_host, kev_count_for_host
```suggestion
from cyhy.db.queries import kev_count_for_host, max_severity_for_host
```

2022-04-05 05:32 UTC, mcdonnnj commented on cyhy/db/queries.py
> +    """Return the number of open tickets that have kev set to true in its details."""
```suggestion
    """Return the number of open tickets that have kev set to true in their details."""
```

2022-04-05 15:01 UTC, mcdonnnj approved these changes

2022-04-05 20:14 UTC, merged